name: asa

description: 2D Canvas Family Tree Designer

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: truename: family_tree_canvas

<<<<<<< HEAD
description: 2D Canvas Family Tree Designer
=======
description: Professional 2D Canvas Family Tree Designer
>>>>>>> 8706cb3 (setup flutter project)

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
<<<<<<< HEAD
  uses-material-design: true
=======
  uses-material-design: true
>>>>>>> 8706cb3 (setup flutter project)
